Repository oasisprotocol/docs, pull requests merged in 2024-12, with the labels that each got.

#1045 docs: Remove deprecated testnets from list of Celer supported networks
  docs/dapp/opl/celer/networks.md
Labels: documentation, good first issue

#1044 chore: Remove redundant words
  docs/dapp/opl/celer/ping-example.md
  docs/dapp/opl/opl-sdk/ping-example.md
  docs/node/testnet/upgrade-log.md
Labels: documentation

#1054 docs: move verification to tools
  docs/dapp/images/tools/sourcify1.png
  docs/dapp/images/tools/sourcify2.png
  docs/dapp/images/tools/sourcify3.png
  docs/dapp/tools/README.mdx
  docs/dapp/tools/abi-playground.md
  docs/dapp/tools/verification.md
  redirects.ts
  sidebarDapp.ts
Labels: documentation

#1052 docs: Remove why page and redirect to OPF
  docs/general/images/oasis-network/compare_networks.png
  docs/general/images/oasis-network/data_tokenization.png
  docs/general/images/oasis-network/ecosystem-defi.jpg
  docs/general/images/oasis-network/ecosystem.jpg
  docs/general/images/oasis-network/features.png
  docs/general/images/oasis-network/lending_market.png
  docs/general/images/oasis-network/partners.png
  docs/general/images/oasis-network/press_logos.png
  docs/general/images/oasis-network/secure_enclave.png
  docs/general/images/oasis-network/team_logos.png
  docs/general/images/oasis-network/timeline.png
  docs/general/images/oasis-network/uni_map.png
  docs/general/oasis-network/README.mdx
  docs/general/oasis-network/why-oasis.md
  redirects.ts
  sidebarGeneral.ts
Labels: documentation, enhancement, good first issue, p:1

#1053 tooling: Specify yarn version via packageManager
  package.json
Labels: p:2
