Repository oasisprotocol/docs, pull requests merged in 2024-09, with the labels that each got.

#940 docs: Improve Emerald and Sapphire content
  docs/dapp/emerald/README.mdx
  docs/dapp/emerald/network.mdx
  docs/dapp/emerald/writing-dapps-on-emerald.mdx
  docs/dapp/tools/README.md
  docs/general/manage-tokens/README.mdx
  docs/general/manage-tokens/how-to-transfer-eth-erc20-to-emerald-paratime.md
  docs/node/mainnet/README.md
  docs/node/web3.mdx
  sidebarDapp.ts
Labels: documentation, enhancement, help wanted, examples

#958 docs: Cloud Providers (that support Intel SGX)
  docs/node/run-your-node/prerequisites/cloud-providers.md
  docs/node/run-your-node/prerequisites/hardware-recommendations.md
  sidebarNode.ts
Labels: documentation, enhancement

#947 docs: update stake requirements
  docs/node/run-your-node/prerequisites/stake-requirements.md
Labels: documentation
